[metadata]
addr = 8279
size = 735
last_change = 1647756913

[stack_vars.-30]
last_change = 1647756913
stack_offset = -48
stack_offset_type = 1
name = "dreamer"
type = "dreamer *"
size = 8
addr = 8279
