[metadata]
addr = 7207
size = 239
last_change = 1647756932

[header]
last_change = 1647756932
name = "create_dream"
addr = 7207
ret_type = "__int64"

[header.args.0]
idx = 0
name = "dreamer"
type_str = "dreamer *"
size = 8
