[metadata]
addr = 7039
size = 168
last_change = 1647756507

[header]
last_change = 1647756507
name = "__nightmare"
addr = 7039
ret_type = "unsigned __int64"

[header.args.0]
idx = 0
name = "a1"
type_str = "char *"
size = 8

[header.args.1]
idx = 1
name = "a2"
type_str = "_BYTE *"
size = 8

[header.args.2]
idx = 2
name = "zero_1"
type_str = "char"
size = 1

[header.args.3]
idx = 3
name = "zero_2"
type_str = "char"
size = 1
