[metadata]
addr = 4937
size = 586
last_change = 1647760844

[header]
last_change = 1647760571
name = "__nightmare_r"
addr = 4937
ret_type = "unsigned __int64"

[stack_vars.-88]
last_change = 1647760844
stack_offset = -136
stack_offset_type = 1
name = "output_arr"
type = "__int8[96]"
size = 96
addr = 4937

[header.args.0]
idx = 0
name = "buf"
type_str = "__int64 *"
size = 8

[header.args.1]
idx = 1
name = "zer0"
type_str = "char"
size = 1

[header.args.2]
idx = 2
name = "a3"
type_str = "char"
size = 1
