[metadata]
name = "dreamer"
size = 216
last_change = 1647756742

[members.0]
member_name = "a1"
offset = 0
type = "unsigned __int8[10][8]"
size = 80

[members.50]
member_name = "padding"
offset = 80
type = "char[40]"
size = 40

[members.78]
member_name = "a2"
offset = 120
type = "unsigned __int8[12][8]"
size = 96
