[metadata]
name = "dreamer"
size = 120
last_change = 1647756670

[members.0]
member_name = "a1"
offset = 0
type = "unsigned __int8[10][8]"
size = 80

[members.50]
member_name = "padding"
offset = 80
type = "char[40]"
size = 40
