[metadata]
name = "dreamer"
size = 82
last_change = 1647756673

[members.0]
member_name = "a1"
offset = 0
type = "unsigned __int8[10][8]"
size = 80

[members.50]
member_name = "padding"
offset = 80
type = ""
size = 2
